<div>
    <span>
        <a>jhbjwbccd</a>
    </span>
    <span>
        <a>jhbjwbccd</a>
    </span>
    <span>
        <a>jhbjwbccd</a>
    </span>
    <div>
        <p> bjhgjh</p>
        <p>
            <ul>
                <li>jckjnw</li>
                <li>kndjne</li>
            </ul>
        </p>
    </div>
</div>